// Code generated by protoc-gen-go. DO NOT EDIT.
// source: invoices.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InvoiceType int32

const (
	InvoiceType_AP InvoiceType = 0
	InvoiceType_AR InvoiceType = 1
)

var InvoiceType_name = map[int32]string{
	0: "AP",
	1: "AR",
}

var InvoiceType_value = map[string]int32{
	"AP": 0,
	"AR": 1,
}

func (x InvoiceType) String() string {
	return proto.EnumName(InvoiceType_name, int32(x))
}

func (InvoiceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{0}
}

//Status Enumeration
type EStatus int32

const (
	EStatus_Error EStatus = 0
	EStatus_Ok    EStatus = 1
)

var EStatus_name = map[int32]string{
	0: "Error",
	1: "Ok",
}

var EStatus_value = map[string]int32{
	"Error": 0,
	"Ok":    1,
}

func (x EStatus) String() string {
	return proto.EnumName(EStatus_name, int32(x))
}

func (EStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{1}
}

type Invoice struct {
	//Data XML file data from Finvoice 1.3 Standard
	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	//Issuer_id Specification UUID type (This identifier is a 128-bit)
	IssuerId uint32 `protobuf:"varint,2,opt,name=Issuer_id,json=IssuerId,proto3" json:"Issuer_id,omitempty"`
	//Attachments are optional pdf files
	Attachments [][]byte `protobuf:"bytes,3,rep,name=Attachments,proto3" json:"Attachments,omitempty"`
	//Type defines the Invoice Type
	Type                 InvoiceType `protobuf:"varint,4,opt,name=Type,proto3,enum=services.InvoiceType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Invoice) Reset()         { *m = Invoice{} }
func (m *Invoice) String() string { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()    {}
func (*Invoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{0}
}

func (m *Invoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoice.Unmarshal(m, b)
}
func (m *Invoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoice.Marshal(b, m, deterministic)
}
func (m *Invoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoice.Merge(m, src)
}
func (m *Invoice) XXX_Size() int {
	return xxx_messageInfo_Invoice.Size(m)
}
func (m *Invoice) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoice.DiscardUnknown(m)
}

var xxx_messageInfo_Invoice proto.InternalMessageInfo

func (m *Invoice) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Invoice) GetIssuerId() uint32 {
	if m != nil {
		return m.IssuerId
	}
	return 0
}

func (m *Invoice) GetAttachments() [][]byte {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *Invoice) GetType() InvoiceType {
	if m != nil {
		return m.Type
	}
	return InvoiceType_AP
}

type InvoicePreview struct {
	Preview              []byte   `protobuf:"bytes,2,opt,name=Preview,proto3" json:"Preview,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvoicePreview) Reset()         { *m = InvoicePreview{} }
func (m *InvoicePreview) String() string { return proto.CompactTextString(m) }
func (*InvoicePreview) ProtoMessage()    {}
func (*InvoicePreview) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{1}
}

func (m *InvoicePreview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoicePreview.Unmarshal(m, b)
}
func (m *InvoicePreview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoicePreview.Marshal(b, m, deterministic)
}
func (m *InvoicePreview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoicePreview.Merge(m, src)
}
func (m *InvoicePreview) XXX_Size() int {
	return xxx_messageInfo_InvoicePreview.Size(m)
}
func (m *InvoicePreview) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoicePreview.DiscardUnknown(m)
}

var xxx_messageInfo_InvoicePreview proto.InternalMessageInfo

func (m *InvoicePreview) GetPreview() []byte {
	if m != nil {
		return m.Preview
	}
	return nil
}

//Attachment pdf files to be sent through stream
type Attachment struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attachment) Reset()         { *m = Attachment{} }
func (m *Attachment) String() string { return proto.CompactTextString(m) }
func (*Attachment) ProtoMessage()    {}
func (*Attachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{2}
}

func (m *Attachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attachment.Unmarshal(m, b)
}
func (m *Attachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attachment.Marshal(b, m, deterministic)
}
func (m *Attachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attachment.Merge(m, src)
}
func (m *Attachment) XXX_Size() int {
	return xxx_messageInfo_Attachment.Size(m)
}
func (m *Attachment) XXX_DiscardUnknown() {
	xxx_messageInfo_Attachment.DiscardUnknown(m)
}

var xxx_messageInfo_Attachment proto.InternalMessageInfo

func (m *Attachment) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

//Response for Invoice services
type Response struct {
	Status               EStatus  `protobuf:"varint,1,opt,name=Status,proto3,enum=services.EStatus" json:"Status,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() EStatus {
	if m != nil {
		return m.Status
	}
	return EStatus_Error
}

func (m *Response) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterEnum("services.InvoiceType", InvoiceType_name, InvoiceType_value)
	proto.RegisterEnum("services.EStatus", EStatus_name, EStatus_value)
	proto.RegisterType((*Invoice)(nil), "services.Invoice")
	proto.RegisterType((*InvoicePreview)(nil), "services.InvoicePreview")
	proto.RegisterType((*Attachment)(nil), "services.Attachment")
	proto.RegisterType((*Response)(nil), "services.Response")
}

func init() { proto.RegisterFile("invoices.proto", fileDescriptor_09d7a0907870ec2e) }

var fileDescriptor_09d7a0907870ec2e = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x4b, 0xeb, 0x50,
	0x10, 0xed, 0x6d, 0xfb, 0xfa, 0x31, 0xed, 0xcb, 0x4b, 0x87, 0x3e, 0x08, 0xef, 0x29, 0x84, 0x2c,
	0x24, 0xed, 0xa2, 0x8b, 0xba, 0x74, 0x63, 0x69, 0x05, 0x0b, 0x8a, 0xe5, 0x6a, 0xd1, 0x9d, 0xc4,
	0x66, 0xc0, 0xa0, 0xe6, 0x86, 0x7b, 0x6f, 0x2b, 0xfe, 0x02, 0xff, 0xa3, 0xbf, 0x46, 0x92, 0xdc,
	0x90, 0x60, 0x75, 0x95, 0x99, 0x73, 0x4e, 0xce, 0x99, 0x99, 0x04, 0xac, 0x28, 0xde, 0x89, 0x68,
	0x43, 0x6a, 0x92, 0x48, 0xa1, 0x05, 0x76, 0x14, 0xc9, 0x5d, 0xda, 0x7b, 0xef, 0x0c, 0xda, 0xcb,
	0x9c, 0x44, 0x84, 0xe6, 0x22, 0xd0, 0x81, 0xc3, 0x5c, 0xe6, 0xf7, 0x79, 0x56, 0xe3, 0x7f, 0xe8,
	0x2e, 0x95, 0xda, 0x92, 0xbc, 0x8f, 0x42, 0xa7, 0xee, 0x32, 0xff, 0x37, 0xef, 0xe4, 0xc0, 0x32,
	0x44, 0x17, 0x7a, 0x33, 0xad, 0x83, 0xcd, 0xe3, 0x0b, 0xc5, 0x5a, 0x39, 0x0d, 0xb7, 0xe1, 0xf7,
	0x79, 0x15, 0xc2, 0x11, 0x34, 0x6f, 0xde, 0x12, 0x72, 0x9a, 0x2e, 0xf3, 0xad, 0xe9, 0xdf, 0x49,
	0x91, 0x3b, 0x31, 0x99, 0x29, 0xc9, 0x33, 0x89, 0x37, 0x06, 0xcb, 0x80, 0x2b, 0x49, 0xbb, 0x88,
	0x5e, 0xd1, 0x81, 0xb6, 0x29, 0xb3, 0xe4, 0x3e, 0x2f, 0x5a, 0xef, 0x08, 0xa0, 0x4c, 0x49, 0x75,
	0x73, 0x11, 0x6b, 0x8a, 0xb5, 0x19, 0xbd, 0x68, 0xbd, 0x5b, 0xe8, 0x70, 0x52, 0x89, 0x88, 0x15,
	0xe1, 0x08, 0x5a, 0xd7, 0x3a, 0xd0, 0x5b, 0x95, 0x89, 0xac, 0xe9, 0xa0, 0x1c, 0x86, 0x72, 0x82,
	0x1b, 0x41, 0xba, 0xd7, 0x82, 0xd4, 0x46, 0x46, 0x89, 0x8e, 0x44, 0x9c, 0x85, 0x77, 0x79, 0x15,
	0x1a, 0x1f, 0x42, 0xaf, 0xb2, 0x01, 0xb6, 0xa0, 0x3e, 0x5b, 0xd9, 0xb5, 0xec, 0xc9, 0x6d, 0x36,
	0x3e, 0x80, 0xb6, 0xf1, 0xc4, 0x2e, 0xfc, 0x3a, 0x93, 0x52, 0xc8, 0x9c, 0xbd, 0x7a, 0xb2, 0xd9,
	0xf4, 0x83, 0xc1, 0x1f, 0xf3, 0xf6, 0x3a, 0x79, 0x16, 0x41, 0x48, 0x12, 0x4f, 0xc0, 0x9e, 0x4b,
	0x0a, 0x34, 0xdd, 0x5d, 0x5e, 0x14, 0xdf, 0x63, 0xb0, 0x77, 0xae, 0x7f, 0x58, 0x42, 0xc5, 0x62,
	0x5e, 0x0d, 0xcf, 0x61, 0xb8, 0x4e, 0xc2, 0x40, 0xd3, 0xd7, 0x03, 0xee, 0x19, 0x18, 0xe6, 0x7b,
	0x1f, 0x9f, 0xe1, 0x29, 0xd8, 0xb9, 0x53, 0xe5, 0xbc, 0xc3, 0x52, 0x5b, 0xa2, 0x3f, 0x39, 0x3c,
	0xb4, 0xb2, 0x3f, 0xec, 0xf8, 0x33, 0x00, 0x00, 0xff, 0xff, 0x00, 0xa1, 0x4d, 0xf9, 0x73, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InvoiceUploaderClient is the client API for InvoiceUploader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InvoiceUploaderClient interface {
	//Service to create XML Invoice
	CreateXMLInvoice(ctx context.Context, in *Invoice, opts ...grpc.CallOption) (*Response, error)
	//Service to upload invoice preview as a stream
	UpdateInvoicePreview(ctx context.Context, opts ...grpc.CallOption) (InvoiceUploader_UpdateInvoicePreviewClient, error)
	//Service to upload invoice attachment as a stream
	UpdateAttachment(ctx context.Context, opts ...grpc.CallOption) (InvoiceUploader_UpdateAttachmentClient, error)
}

type invoiceUploaderClient struct {
	cc *grpc.ClientConn
}

func NewInvoiceUploaderClient(cc *grpc.ClientConn) InvoiceUploaderClient {
	return &invoiceUploaderClient{cc}
}

func (c *invoiceUploaderClient) CreateXMLInvoice(ctx context.Context, in *Invoice, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/services.InvoiceUploader/CreateXMLInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceUploaderClient) UpdateInvoicePreview(ctx context.Context, opts ...grpc.CallOption) (InvoiceUploader_UpdateInvoicePreviewClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InvoiceUploader_serviceDesc.Streams[0], "/services.InvoiceUploader/UpdateInvoicePreview", opts...)
	if err != nil {
		return nil, err
	}
	x := &invoiceUploaderUpdateInvoicePreviewClient{stream}
	return x, nil
}

type InvoiceUploader_UpdateInvoicePreviewClient interface {
	Send(*InvoicePreview) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type invoiceUploaderUpdateInvoicePreviewClient struct {
	grpc.ClientStream
}

func (x *invoiceUploaderUpdateInvoicePreviewClient) Send(m *InvoicePreview) error {
	return x.ClientStream.SendMsg(m)
}

func (x *invoiceUploaderUpdateInvoicePreviewClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *invoiceUploaderClient) UpdateAttachment(ctx context.Context, opts ...grpc.CallOption) (InvoiceUploader_UpdateAttachmentClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InvoiceUploader_serviceDesc.Streams[1], "/services.InvoiceUploader/UpdateAttachment", opts...)
	if err != nil {
		return nil, err
	}
	x := &invoiceUploaderUpdateAttachmentClient{stream}
	return x, nil
}

type InvoiceUploader_UpdateAttachmentClient interface {
	Send(*Attachment) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type invoiceUploaderUpdateAttachmentClient struct {
	grpc.ClientStream
}

func (x *invoiceUploaderUpdateAttachmentClient) Send(m *Attachment) error {
	return x.ClientStream.SendMsg(m)
}

func (x *invoiceUploaderUpdateAttachmentClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InvoiceUploaderServer is the server API for InvoiceUploader service.
type InvoiceUploaderServer interface {
	//Service to create XML Invoice
	CreateXMLInvoice(context.Context, *Invoice) (*Response, error)
	//Service to upload invoice preview as a stream
	UpdateInvoicePreview(InvoiceUploader_UpdateInvoicePreviewServer) error
	//Service to upload invoice attachment as a stream
	UpdateAttachment(InvoiceUploader_UpdateAttachmentServer) error
}

// UnimplementedInvoiceUploaderServer can be embedded to have forward compatible implementations.
type UnimplementedInvoiceUploaderServer struct {
}

func (*UnimplementedInvoiceUploaderServer) CreateXMLInvoice(ctx context.Context, req *Invoice) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateXMLInvoice not implemented")
}
func (*UnimplementedInvoiceUploaderServer) UpdateInvoicePreview(srv InvoiceUploader_UpdateInvoicePreviewServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateInvoicePreview not implemented")
}
func (*UnimplementedInvoiceUploaderServer) UpdateAttachment(srv InvoiceUploader_UpdateAttachmentServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateAttachment not implemented")
}

func RegisterInvoiceUploaderServer(s *grpc.Server, srv InvoiceUploaderServer) {
	s.RegisterService(&_InvoiceUploader_serviceDesc, srv)
}

func _InvoiceUploader_CreateXMLInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Invoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceUploaderServer).CreateXMLInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.InvoiceUploader/CreateXMLInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceUploaderServer).CreateXMLInvoice(ctx, req.(*Invoice))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceUploader_UpdateInvoicePreview_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InvoiceUploaderServer).UpdateInvoicePreview(&invoiceUploaderUpdateInvoicePreviewServer{stream})
}

type InvoiceUploader_UpdateInvoicePreviewServer interface {
	SendAndClose(*Response) error
	Recv() (*InvoicePreview, error)
	grpc.ServerStream
}

type invoiceUploaderUpdateInvoicePreviewServer struct {
	grpc.ServerStream
}

func (x *invoiceUploaderUpdateInvoicePreviewServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *invoiceUploaderUpdateInvoicePreviewServer) Recv() (*InvoicePreview, error) {
	m := new(InvoicePreview)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _InvoiceUploader_UpdateAttachment_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InvoiceUploaderServer).UpdateAttachment(&invoiceUploaderUpdateAttachmentServer{stream})
}

type InvoiceUploader_UpdateAttachmentServer interface {
	SendAndClose(*Response) error
	Recv() (*Attachment, error)
	grpc.ServerStream
}

type invoiceUploaderUpdateAttachmentServer struct {
	grpc.ServerStream
}

func (x *invoiceUploaderUpdateAttachmentServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *invoiceUploaderUpdateAttachmentServer) Recv() (*Attachment, error) {
	m := new(Attachment)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _InvoiceUploader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.InvoiceUploader",
	HandlerType: (*InvoiceUploaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateXMLInvoice",
			Handler:    _InvoiceUploader_CreateXMLInvoice_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateInvoicePreview",
			Handler:       _InvoiceUploader_UpdateInvoicePreview_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UpdateAttachment",
			Handler:       _InvoiceUploader_UpdateAttachment_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "invoices.proto",
}
