// Code generated by protoc-gen-go. DO NOT EDIT.
// source: invoices.proto

package services

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Identifies the AP or AR Invoice Types
type InvoiceType int32

const (
	InvoiceType_AP InvoiceType = 0
	InvoiceType_AR InvoiceType = 1
)

var InvoiceType_name = map[int32]string{
	0: "AP",
	1: "AR",
}

var InvoiceType_value = map[string]int32{
	"AP": 0,
	"AR": 1,
}

func (x InvoiceType) String() string {
	return proto.EnumName(InvoiceType_name, int32(x))
}

func (InvoiceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{0}
}

//Status Enumeration
type EStatus int32

const (
	EStatus_Error EStatus = 0
	EStatus_Ok    EStatus = 1
)

var EStatus_name = map[int32]string{
	0: "Error",
	1: "Ok",
}

var EStatus_value = map[string]int32{
	"Error": 0,
	"Ok":    1,
}

func (x EStatus) String() string {
	return proto.EnumName(EStatus_name, int32(x))
}

func (EStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{1}
}

type CounterPartyVAT struct {
	VAT                  string      `protobuf:"bytes,1,opt,name=VAT,proto3" json:"VAT,omitempty"`
	Country              string      `protobuf:"bytes,2,opt,name=Country,proto3" json:"Country,omitempty"`
	InvoiceNumber        int64       `protobuf:"varint,3,opt,name=InvoiceNumber,proto3" json:"InvoiceNumber,omitempty"`
	Type                 InvoiceType `protobuf:"varint,4,opt,name=Type,proto3,enum=services.InvoiceType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CounterPartyVAT) Reset()         { *m = CounterPartyVAT{} }
func (m *CounterPartyVAT) String() string { return proto.CompactTextString(m) }
func (*CounterPartyVAT) ProtoMessage()    {}
func (*CounterPartyVAT) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{0}
}

func (m *CounterPartyVAT) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CounterPartyVAT.Unmarshal(m, b)
}
func (m *CounterPartyVAT) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CounterPartyVAT.Marshal(b, m, deterministic)
}
func (m *CounterPartyVAT) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CounterPartyVAT.Merge(m, src)
}
func (m *CounterPartyVAT) XXX_Size() int {
	return xxx_messageInfo_CounterPartyVAT.Size(m)
}
func (m *CounterPartyVAT) XXX_DiscardUnknown() {
	xxx_messageInfo_CounterPartyVAT.DiscardUnknown(m)
}

var xxx_messageInfo_CounterPartyVAT proto.InternalMessageInfo

func (m *CounterPartyVAT) GetVAT() string {
	if m != nil {
		return m.VAT
	}
	return ""
}

func (m *CounterPartyVAT) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *CounterPartyVAT) GetInvoiceNumber() int64 {
	if m != nil {
		return m.InvoiceNumber
	}
	return 0
}

func (m *CounterPartyVAT) GetType() InvoiceType {
	if m != nil {
		return m.Type
	}
	return InvoiceType_AP
}

type QueryAttachment struct {
	Filename             string   `protobuf:"bytes,1,opt,name=Filename,proto3" json:"Filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryAttachment) Reset()         { *m = QueryAttachment{} }
func (m *QueryAttachment) String() string { return proto.CompactTextString(m) }
func (*QueryAttachment) ProtoMessage()    {}
func (*QueryAttachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{1}
}

func (m *QueryAttachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryAttachment.Unmarshal(m, b)
}
func (m *QueryAttachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryAttachment.Marshal(b, m, deterministic)
}
func (m *QueryAttachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttachment.Merge(m, src)
}
func (m *QueryAttachment) XXX_Size() int {
	return xxx_messageInfo_QueryAttachment.Size(m)
}
func (m *QueryAttachment) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttachment.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttachment proto.InternalMessageInfo

func (m *QueryAttachment) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

type QueryInvoice struct {
	InvoiceNumber        int64    `protobuf:"varint,1,opt,name=InvoiceNumber,proto3" json:"InvoiceNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QueryInvoice) Reset()         { *m = QueryInvoice{} }
func (m *QueryInvoice) String() string { return proto.CompactTextString(m) }
func (*QueryInvoice) ProtoMessage()    {}
func (*QueryInvoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{2}
}

func (m *QueryInvoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QueryInvoice.Unmarshal(m, b)
}
func (m *QueryInvoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QueryInvoice.Marshal(b, m, deterministic)
}
func (m *QueryInvoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInvoice.Merge(m, src)
}
func (m *QueryInvoice) XXX_Size() int {
	return xxx_messageInfo_QueryInvoice.Size(m)
}
func (m *QueryInvoice) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInvoice.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInvoice proto.InternalMessageInfo

func (m *QueryInvoice) GetInvoiceNumber() int64 {
	if m != nil {
		return m.InvoiceNumber
	}
	return 0
}

type AttachmentsResponse struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	InvoiceNumber        int64    `protobuf:"varint,2,opt,name=InvoiceNumber,proto3" json:"InvoiceNumber,omitempty"`
	Filename             string   `protobuf:"bytes,3,opt,name=Filename,proto3" json:"Filename,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachmentsResponse) Reset()         { *m = AttachmentsResponse{} }
func (m *AttachmentsResponse) String() string { return proto.CompactTextString(m) }
func (*AttachmentsResponse) ProtoMessage()    {}
func (*AttachmentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{3}
}

func (m *AttachmentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachmentsResponse.Unmarshal(m, b)
}
func (m *AttachmentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachmentsResponse.Marshal(b, m, deterministic)
}
func (m *AttachmentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachmentsResponse.Merge(m, src)
}
func (m *AttachmentsResponse) XXX_Size() int {
	return xxx_messageInfo_AttachmentsResponse.Size(m)
}
func (m *AttachmentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachmentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttachmentsResponse proto.InternalMessageInfo

func (m *AttachmentsResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AttachmentsResponse) GetInvoiceNumber() int64 {
	if m != nil {
		return m.InvoiceNumber
	}
	return 0
}

func (m *AttachmentsResponse) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

// Invoice is the invoice creation input
type Invoice struct {
	//Data XML file data from Finvoice 1.3 Standard
	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	//Issuer_id Specification UUID type (This identifier is a 128-bit)
	IssuerId string `protobuf:"bytes,2,opt,name=Issuer_id,json=IssuerId,proto3" json:"Issuer_id,omitempty"`
	//Attachments are optional pdf files
	Attachments [][]byte `protobuf:"bytes,3,rep,name=Attachments,proto3" json:"Attachments,omitempty"`
	//Type defines the Invoice Type
	Type                 InvoiceType `protobuf:"varint,4,opt,name=Type,proto3,enum=services.InvoiceType" json:"Type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Invoice) Reset()         { *m = Invoice{} }
func (m *Invoice) String() string { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()    {}
func (*Invoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{4}
}

func (m *Invoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Invoice.Unmarshal(m, b)
}
func (m *Invoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Invoice.Marshal(b, m, deterministic)
}
func (m *Invoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Invoice.Merge(m, src)
}
func (m *Invoice) XXX_Size() int {
	return xxx_messageInfo_Invoice.Size(m)
}
func (m *Invoice) XXX_DiscardUnknown() {
	xxx_messageInfo_Invoice.DiscardUnknown(m)
}

var xxx_messageInfo_Invoice proto.InternalMessageInfo

func (m *Invoice) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Invoice) GetIssuerId() string {
	if m != nil {
		return m.IssuerId
	}
	return ""
}

func (m *Invoice) GetAttachments() [][]byte {
	if m != nil {
		return m.Attachments
	}
	return nil
}

func (m *Invoice) GetType() InvoiceType {
	if m != nil {
		return m.Type
	}
	return InvoiceType_AP
}

type InvoicePreview struct {
	InvoiceNumber        int64    `protobuf:"varint,1,opt,name=InvoiceNumber,proto3" json:"InvoiceNumber,omitempty"`
	Preview              []byte   `protobuf:"bytes,2,opt,name=Preview,proto3" json:"Preview,omitempty"`
	IssuerId             string   `protobuf:"bytes,3,opt,name=Issuer_id,json=IssuerId,proto3" json:"Issuer_id,omitempty"`
	CounterpartyVat      string   `protobuf:"bytes,4,opt,name=CounterpartyVat,proto3" json:"CounterpartyVat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvoicePreview) Reset()         { *m = InvoicePreview{} }
func (m *InvoicePreview) String() string { return proto.CompactTextString(m) }
func (*InvoicePreview) ProtoMessage()    {}
func (*InvoicePreview) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{5}
}

func (m *InvoicePreview) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvoicePreview.Unmarshal(m, b)
}
func (m *InvoicePreview) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvoicePreview.Marshal(b, m, deterministic)
}
func (m *InvoicePreview) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvoicePreview.Merge(m, src)
}
func (m *InvoicePreview) XXX_Size() int {
	return xxx_messageInfo_InvoicePreview.Size(m)
}
func (m *InvoicePreview) XXX_DiscardUnknown() {
	xxx_messageInfo_InvoicePreview.DiscardUnknown(m)
}

var xxx_messageInfo_InvoicePreview proto.InternalMessageInfo

func (m *InvoicePreview) GetInvoiceNumber() int64 {
	if m != nil {
		return m.InvoiceNumber
	}
	return 0
}

func (m *InvoicePreview) GetPreview() []byte {
	if m != nil {
		return m.Preview
	}
	return nil
}

func (m *InvoicePreview) GetIssuerId() string {
	if m != nil {
		return m.IssuerId
	}
	return ""
}

func (m *InvoicePreview) GetCounterpartyVat() string {
	if m != nil {
		return m.CounterpartyVat
	}
	return ""
}

//Attachment pdf files to be sent through stream
type Attachment struct {
	InvoiceNumber        int64    `protobuf:"varint,1,opt,name=InvoiceNumber,proto3" json:"InvoiceNumber,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=Content,proto3" json:"Content,omitempty"`
	IssuerId             string   `protobuf:"bytes,3,opt,name=Issuer_id,json=IssuerId,proto3" json:"Issuer_id,omitempty"`
	CounterpartyVat      string   `protobuf:"bytes,4,opt,name=CounterpartyVat,proto3" json:"CounterpartyVat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attachment) Reset()         { *m = Attachment{} }
func (m *Attachment) String() string { return proto.CompactTextString(m) }
func (*Attachment) ProtoMessage()    {}
func (*Attachment) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{6}
}

func (m *Attachment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attachment.Unmarshal(m, b)
}
func (m *Attachment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attachment.Marshal(b, m, deterministic)
}
func (m *Attachment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attachment.Merge(m, src)
}
func (m *Attachment) XXX_Size() int {
	return xxx_messageInfo_Attachment.Size(m)
}
func (m *Attachment) XXX_DiscardUnknown() {
	xxx_messageInfo_Attachment.DiscardUnknown(m)
}

var xxx_messageInfo_Attachment proto.InternalMessageInfo

func (m *Attachment) GetInvoiceNumber() int64 {
	if m != nil {
		return m.InvoiceNumber
	}
	return 0
}

func (m *Attachment) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *Attachment) GetIssuerId() string {
	if m != nil {
		return m.IssuerId
	}
	return ""
}

func (m *Attachment) GetCounterpartyVat() string {
	if m != nil {
		return m.CounterpartyVat
	}
	return ""
}

//Response for Invoice services
type Response struct {
	Status               EStatus  `protobuf:"varint,1,opt,name=Status,proto3,enum=services.EStatus" json:"Status,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=Description,proto3" json:"Description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{7}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() EStatus {
	if m != nil {
		return m.Status
	}
	return EStatus_Error
}

func (m *Response) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

//InternalInvoice is the simplified Invoice for internal usage
type InternalInvoice struct {
	Type                 InvoiceType `protobuf:"varint,1,opt,name=Type,proto3,enum=services.InvoiceType" json:"Type,omitempty"`
	CustomerID           string      `protobuf:"bytes,2,opt,name=CustomerID,proto3" json:"CustomerID,omitempty"`
	InvoiceNumber        int64       `protobuf:"varint,3,opt,name=InvoiceNumber,proto3" json:"InvoiceNumber,omitempty"`
	Currency             string      `protobuf:"bytes,4,opt,name=Currency,proto3" json:"Currency,omitempty"`
	FaceValue            int64       `protobuf:"varint,5,opt,name=FaceValue,proto3" json:"FaceValue,omitempty"`
	CounterPartyVAT      string      `protobuf:"bytes,6,opt,name=CounterPartyVAT,proto3" json:"CounterPartyVAT,omitempty"`
	CounterPartyCountry  string      `protobuf:"bytes,7,opt,name=CounterPartyCountry,proto3" json:"CounterPartyCountry,omitempty"`
	IssueDate            string      `protobuf:"bytes,8,opt,name=IssueDate,proto3" json:"IssueDate,omitempty"`
	DueDate              string      `protobuf:"bytes,9,opt,name=DueDate,proto3" json:"DueDate,omitempty"`
	ValidVAT             bool        `protobuf:"varint,10,opt,name=ValidVAT,proto3" json:"ValidVAT,omitempty"`
	InvoiceFile          []byte      `protobuf:"bytes,11,opt,name=InvoiceFile,proto3" json:"InvoiceFile,omitempty"`
	CompanyName          string      `protobuf:"bytes,12,opt,name=CompanyName,proto3" json:"CompanyName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *InternalInvoice) Reset()         { *m = InternalInvoice{} }
func (m *InternalInvoice) String() string { return proto.CompactTextString(m) }
func (*InternalInvoice) ProtoMessage()    {}
func (*InternalInvoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_09d7a0907870ec2e, []int{8}
}

func (m *InternalInvoice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalInvoice.Unmarshal(m, b)
}
func (m *InternalInvoice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalInvoice.Marshal(b, m, deterministic)
}
func (m *InternalInvoice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalInvoice.Merge(m, src)
}
func (m *InternalInvoice) XXX_Size() int {
	return xxx_messageInfo_InternalInvoice.Size(m)
}
func (m *InternalInvoice) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalInvoice.DiscardUnknown(m)
}

var xxx_messageInfo_InternalInvoice proto.InternalMessageInfo

func (m *InternalInvoice) GetType() InvoiceType {
	if m != nil {
		return m.Type
	}
	return InvoiceType_AP
}

func (m *InternalInvoice) GetCustomerID() string {
	if m != nil {
		return m.CustomerID
	}
	return ""
}

func (m *InternalInvoice) GetInvoiceNumber() int64 {
	if m != nil {
		return m.InvoiceNumber
	}
	return 0
}

func (m *InternalInvoice) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *InternalInvoice) GetFaceValue() int64 {
	if m != nil {
		return m.FaceValue
	}
	return 0
}

func (m *InternalInvoice) GetCounterPartyVAT() string {
	if m != nil {
		return m.CounterPartyVAT
	}
	return ""
}

func (m *InternalInvoice) GetCounterPartyCountry() string {
	if m != nil {
		return m.CounterPartyCountry
	}
	return ""
}

func (m *InternalInvoice) GetIssueDate() string {
	if m != nil {
		return m.IssueDate
	}
	return ""
}

func (m *InternalInvoice) GetDueDate() string {
	if m != nil {
		return m.DueDate
	}
	return ""
}

func (m *InternalInvoice) GetValidVAT() bool {
	if m != nil {
		return m.ValidVAT
	}
	return false
}

func (m *InternalInvoice) GetInvoiceFile() []byte {
	if m != nil {
		return m.InvoiceFile
	}
	return nil
}

func (m *InternalInvoice) GetCompanyName() string {
	if m != nil {
		return m.CompanyName
	}
	return ""
}

func init() {
	proto.RegisterEnum("services.InvoiceType", InvoiceType_name, InvoiceType_value)
	proto.RegisterEnum("services.EStatus", EStatus_name, EStatus_value)
	proto.RegisterType((*CounterPartyVAT)(nil), "services.CounterPartyVAT")
	proto.RegisterType((*QueryAttachment)(nil), "services.QueryAttachment")
	proto.RegisterType((*QueryInvoice)(nil), "services.QueryInvoice")
	proto.RegisterType((*AttachmentsResponse)(nil), "services.AttachmentsResponse")
	proto.RegisterType((*Invoice)(nil), "services.Invoice")
	proto.RegisterType((*InvoicePreview)(nil), "services.InvoicePreview")
	proto.RegisterType((*Attachment)(nil), "services.Attachment")
	proto.RegisterType((*Response)(nil), "services.Response")
	proto.RegisterType((*InternalInvoice)(nil), "services.InternalInvoice")
}

func init() { proto.RegisterFile("invoices.proto", fileDescriptor_09d7a0907870ec2e) }

var fileDescriptor_09d7a0907870ec2e = []byte{
	// 718 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xee, 0xc6, 0x6d, 0x7e, 0xa6, 0x69, 0x9a, 0x6e, 0x5b, 0x64, 0x42, 0x8b, 0x22, 0x8b, 0x43,
	0x5a, 0x89, 0xaa, 0x0a, 0xdc, 0xb8, 0x10, 0x25, 0xb4, 0x8d, 0xa0, 0xa5, 0x98, 0x36, 0x70, 0x43,
	0xdb, 0x64, 0x24, 0xac, 0x26, 0xb6, 0xb5, 0x5e, 0x17, 0xe5, 0x09, 0xb8, 0x71, 0xe1, 0xc0, 0x0b,
	0xf0, 0x00, 0x3c, 0x1d, 0x67, 0xb4, 0xeb, 0xf5, 0x4f, 0x9c, 0x54, 0x04, 0x89, 0x53, 0x32, 0xdf,
	0xce, 0x7e, 0xfb, 0xcd, 0x7c, 0xb3, 0x6b, 0xa8, 0x39, 0xee, 0x9d, 0xe7, 0x0c, 0x31, 0x38, 0xf2,
	0xb9, 0x27, 0x3c, 0x5a, 0x0e, 0x90, 0xdf, 0xc9, 0xd8, 0xfa, 0x46, 0x60, 0xb3, 0xeb, 0x85, 0xae,
	0x40, 0x7e, 0xc9, 0xb8, 0x98, 0x0e, 0x3a, 0x57, 0xb4, 0x0e, 0xc6, 0xa0, 0x73, 0x65, 0x92, 0x26,
	0x69, 0x55, 0x6c, 0xf9, 0x97, 0x9a, 0x50, 0x52, 0x49, 0x7c, 0x6a, 0x16, 0x14, 0x1a, 0x87, 0xf4,
	0x09, 0x6c, 0xf4, 0x23, 0xee, 0x8b, 0x70, 0x72, 0x83, 0xdc, 0x34, 0x9a, 0xa4, 0x65, 0xd8, 0xb3,
	0x20, 0x3d, 0x80, 0xd5, 0xab, 0xa9, 0x8f, 0xe6, 0x6a, 0x93, 0xb4, 0x6a, 0xed, 0xdd, 0xa3, 0xf8,
	0xf8, 0x23, 0x9d, 0x26, 0x17, 0x6d, 0x95, 0x62, 0x3d, 0x85, 0xcd, 0x77, 0x21, 0xf2, 0x69, 0x47,
	0x08, 0x36, 0xfc, 0x3c, 0x41, 0x57, 0xd0, 0x06, 0x94, 0x4f, 0x9c, 0x31, 0xba, 0x6c, 0x82, 0x5a,
	0x54, 0x12, 0x5b, 0xcf, 0xa1, 0xaa, 0xd2, 0x35, 0xd1, 0xbc, 0x1e, 0xb2, 0x40, 0x8f, 0x75, 0x0b,
	0xdb, 0x29, 0x7f, 0x60, 0x63, 0xe0, 0x7b, 0x6e, 0x80, 0x94, 0xc2, 0x6a, 0x8f, 0x09, 0xa6, 0xf6,
	0x54, 0x6d, 0xf5, 0x7f, 0x9e, 0xb0, 0xb0, 0xa8, 0xc0, 0xac, 0x44, 0x23, 0x27, 0xf1, 0x2b, 0x81,
	0x52, 0x2c, 0x6f, 0xd1, 0x09, 0x8f, 0xa0, 0xd2, 0x0f, 0x82, 0x10, 0xf9, 0x27, 0x67, 0xa4, 0xdb,
	0x5b, 0x8e, 0x80, 0xfe, 0x88, 0x36, 0x61, 0x3d, 0xa3, 0xd4, 0x34, 0x9a, 0x46, 0xab, 0x6a, 0x67,
	0xa1, 0x7f, 0xe9, 0xed, 0x0f, 0x02, 0x35, 0x8d, 0x5e, 0x72, 0xbc, 0x73, 0xf0, 0xcb, 0x72, 0xfd,
	0x92, 0xfe, 0xeb, 0x0d, 0x4a, 0x60, 0xd5, 0x8e, 0xc3, 0x59, 0xf1, 0x46, 0x4e, 0x7c, 0x2b, 0x99,
	0x2d, 0x5f, 0xcd, 0x16, 0x13, 0x4a, 0x65, 0xc5, 0xce, 0xc3, 0xd6, 0x77, 0x02, 0x90, 0x71, 0x7c,
	0x69, 0x55, 0x5d, 0xcf, 0x15, 0xe8, 0x8a, 0x58, 0x95, 0x0e, 0xff, 0x97, 0xaa, 0x0f, 0x50, 0x4e,
	0x66, 0xe3, 0x00, 0x8a, 0xef, 0x05, 0x13, 0x61, 0xa0, 0xb4, 0xd4, 0xda, 0x5b, 0x69, 0xa3, 0x31,
	0x5a, 0xb0, 0x75, 0x82, 0xf4, 0xac, 0x87, 0xc1, 0x90, 0x3b, 0xbe, 0x70, 0x3c, 0x57, 0x5b, 0x9a,
	0x85, 0xac, 0x5f, 0x06, 0x6c, 0xf6, 0xe5, 0x51, 0x2e, 0x1b, 0xc7, 0xa3, 0x11, 0xfb, 0x48, 0xfe,
	0xea, 0x23, 0x7d, 0x0c, 0xd0, 0x0d, 0x03, 0xe1, 0x4d, 0x90, 0xf7, 0x7b, 0x9a, 0x3f, 0x83, 0x2c,
	0x79, 0x29, 0x1b, 0x50, 0xee, 0x86, 0x9c, 0xa3, 0x3b, 0x9c, 0xea, 0x06, 0x24, 0x31, 0xdd, 0x83,
	0xca, 0x09, 0x1b, 0xe2, 0x80, 0x8d, 0x43, 0x34, 0xd7, 0xd4, 0xee, 0x14, 0xc8, 0x74, 0x30, 0x7e,
	0x33, 0xcc, 0xe2, 0x4c, 0x07, 0x93, 0xa7, 0xe4, 0x18, 0xb6, 0xb3, 0x50, 0xfc, 0x88, 0x94, 0x54,
	0xf6, 0xa2, 0x25, 0x79, 0xb2, 0x72, 0xaa, 0xc7, 0x04, 0x9a, 0x65, 0x95, 0x97, 0x02, 0xd2, 0xf2,
	0x9e, 0x5e, 0xab, 0x44, 0x0f, 0x91, 0x0e, 0x65, 0x35, 0x03, 0x36, 0x76, 0x46, 0x52, 0x0c, 0x34,
	0x49, 0xab, 0x6c, 0x27, 0xb1, 0x34, 0x44, 0x97, 0x2e, 0x2f, 0xa5, 0xb9, 0xae, 0x86, 0x25, 0x0b,
	0xc9, 0x8c, 0xae, 0x37, 0xf1, 0x99, 0x3b, 0xbd, 0x90, 0x57, 0xb8, 0x1a, 0x59, 0x96, 0x81, 0x0e,
	0xf7, 0x13, 0x0e, 0x65, 0x41, 0x11, 0x0a, 0x9d, 0xcb, 0xfa, 0x8a, 0xfa, 0xb5, 0xeb, 0xe4, 0x70,
	0x0f, 0x4a, 0x7a, 0x0c, 0x68, 0x05, 0xd6, 0x5e, 0x71, 0xee, 0xf1, 0x68, 0xf5, 0xed, 0x6d, 0x9d,
	0xb4, 0x7f, 0x16, 0xa4, 0xdf, 0x6a, 0xf7, 0xb5, 0x3f, 0xf6, 0xd8, 0x08, 0x39, 0x7d, 0x01, 0xf5,
	0x2e, 0x47, 0x26, 0xf0, 0xe3, 0xf9, 0x9b, 0x78, 0x06, 0xb6, 0xe6, 0x5c, 0x6f, 0xd0, 0x14, 0x8a,
	0x67, 0xd1, 0x5a, 0xa1, 0x67, 0xb0, 0x73, 0xed, 0x8f, 0x98, 0xc0, 0xdc, 0x75, 0x36, 0xe7, 0x08,
	0xf4, 0xca, 0x62, 0x9e, 0x16, 0xa1, 0x2f, 0xa1, 0x1e, 0x31, 0x65, 0xae, 0xdf, 0x4e, 0x9a, 0x9b,
	0xa2, 0xf7, 0x32, 0x9c, 0xc1, 0x6e, 0xc4, 0x90, 0x37, 0xff, 0x61, 0xba, 0x21, 0xb7, 0xb4, 0x98,
	0xab, 0xfd, 0x9b, 0x24, 0x83, 0x7b, 0x8a, 0x42, 0x20, 0xa7, 0x7d, 0xd8, 0x3a, 0x45, 0x91, 0x2b,
	0xf2, 0x41, 0xba, 0x39, 0xfb, 0xf6, 0x37, 0xee, 0x2d, 0xde, 0x5a, 0x39, 0x26, 0xf4, 0x35, 0xd4,
	0x4e, 0x51, 0x64, 0x5f, 0xce, 0xfb, 0x78, 0xf6, 0x17, 0x95, 0x1f, 0xa4, 0x3a, 0x8f, 0x09, 0x3d,
	0x87, 0x8d, 0x19, 0xb2, 0x6c, 0xad, 0xb9, 0xcf, 0xd7, 0x12, 0x74, 0x37, 0x45, 0xf5, 0x59, 0x7e,
	0xf6, 0x27, 0x00, 0x00, 0xff, 0xff, 0x9b, 0x6a, 0xc3, 0xc4, 0xa8, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// InvoiceUploaderClient is the client API for InvoiceUploader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InvoiceUploaderClient interface {
	//Service to create XML Invoice
	CreateXMLInvoice(ctx context.Context, in *Invoice, opts ...grpc.CallOption) (*Response, error)
	//Service to upload invoice preview as a stream
	UpdateInvoicePreview(ctx context.Context, opts ...grpc.CallOption) (InvoiceUploader_UpdateInvoicePreviewClient, error)
	//Service to upload invoice attachment as a stream
	UpdateAttachment(ctx context.Context, opts ...grpc.CallOption) (InvoiceUploader_UpdateAttachmentClient, error)
	UpdateCounterPartyVAT(ctx context.Context, in *CounterPartyVAT, opts ...grpc.CallOption) (*Response, error)
}

type invoiceUploaderClient struct {
	cc *grpc.ClientConn
}

func NewInvoiceUploaderClient(cc *grpc.ClientConn) InvoiceUploaderClient {
	return &invoiceUploaderClient{cc}
}

func (c *invoiceUploaderClient) CreateXMLInvoice(ctx context.Context, in *Invoice, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/services.InvoiceUploader/CreateXMLInvoice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *invoiceUploaderClient) UpdateInvoicePreview(ctx context.Context, opts ...grpc.CallOption) (InvoiceUploader_UpdateInvoicePreviewClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InvoiceUploader_serviceDesc.Streams[0], "/services.InvoiceUploader/UpdateInvoicePreview", opts...)
	if err != nil {
		return nil, err
	}
	x := &invoiceUploaderUpdateInvoicePreviewClient{stream}
	return x, nil
}

type InvoiceUploader_UpdateInvoicePreviewClient interface {
	Send(*InvoicePreview) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type invoiceUploaderUpdateInvoicePreviewClient struct {
	grpc.ClientStream
}

func (x *invoiceUploaderUpdateInvoicePreviewClient) Send(m *InvoicePreview) error {
	return x.ClientStream.SendMsg(m)
}

func (x *invoiceUploaderUpdateInvoicePreviewClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *invoiceUploaderClient) UpdateAttachment(ctx context.Context, opts ...grpc.CallOption) (InvoiceUploader_UpdateAttachmentClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InvoiceUploader_serviceDesc.Streams[1], "/services.InvoiceUploader/UpdateAttachment", opts...)
	if err != nil {
		return nil, err
	}
	x := &invoiceUploaderUpdateAttachmentClient{stream}
	return x, nil
}

type InvoiceUploader_UpdateAttachmentClient interface {
	Send(*Attachment) error
	CloseAndRecv() (*Response, error)
	grpc.ClientStream
}

type invoiceUploaderUpdateAttachmentClient struct {
	grpc.ClientStream
}

func (x *invoiceUploaderUpdateAttachmentClient) Send(m *Attachment) error {
	return x.ClientStream.SendMsg(m)
}

func (x *invoiceUploaderUpdateAttachmentClient) CloseAndRecv() (*Response, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Response)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *invoiceUploaderClient) UpdateCounterPartyVAT(ctx context.Context, in *CounterPartyVAT, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/services.InvoiceUploader/UpdateCounterPartyVAT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InvoiceUploaderServer is the server API for InvoiceUploader service.
type InvoiceUploaderServer interface {
	//Service to create XML Invoice
	CreateXMLInvoice(context.Context, *Invoice) (*Response, error)
	//Service to upload invoice preview as a stream
	UpdateInvoicePreview(InvoiceUploader_UpdateInvoicePreviewServer) error
	//Service to upload invoice attachment as a stream
	UpdateAttachment(InvoiceUploader_UpdateAttachmentServer) error
	UpdateCounterPartyVAT(context.Context, *CounterPartyVAT) (*Response, error)
}

// UnimplementedInvoiceUploaderServer can be embedded to have forward compatible implementations.
type UnimplementedInvoiceUploaderServer struct {
}

func (*UnimplementedInvoiceUploaderServer) CreateXMLInvoice(ctx context.Context, req *Invoice) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateXMLInvoice not implemented")
}
func (*UnimplementedInvoiceUploaderServer) UpdateInvoicePreview(srv InvoiceUploader_UpdateInvoicePreviewServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateInvoicePreview not implemented")
}
func (*UnimplementedInvoiceUploaderServer) UpdateAttachment(srv InvoiceUploader_UpdateAttachmentServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateAttachment not implemented")
}
func (*UnimplementedInvoiceUploaderServer) UpdateCounterPartyVAT(ctx context.Context, req *CounterPartyVAT) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCounterPartyVAT not implemented")
}

func RegisterInvoiceUploaderServer(s *grpc.Server, srv InvoiceUploaderServer) {
	s.RegisterService(&_InvoiceUploader_serviceDesc, srv)
}

func _InvoiceUploader_CreateXMLInvoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Invoice)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceUploaderServer).CreateXMLInvoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.InvoiceUploader/CreateXMLInvoice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceUploaderServer).CreateXMLInvoice(ctx, req.(*Invoice))
	}
	return interceptor(ctx, in, info, handler)
}

func _InvoiceUploader_UpdateInvoicePreview_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InvoiceUploaderServer).UpdateInvoicePreview(&invoiceUploaderUpdateInvoicePreviewServer{stream})
}

type InvoiceUploader_UpdateInvoicePreviewServer interface {
	SendAndClose(*Response) error
	Recv() (*InvoicePreview, error)
	grpc.ServerStream
}

type invoiceUploaderUpdateInvoicePreviewServer struct {
	grpc.ServerStream
}

func (x *invoiceUploaderUpdateInvoicePreviewServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *invoiceUploaderUpdateInvoicePreviewServer) Recv() (*InvoicePreview, error) {
	m := new(InvoicePreview)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _InvoiceUploader_UpdateAttachment_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(InvoiceUploaderServer).UpdateAttachment(&invoiceUploaderUpdateAttachmentServer{stream})
}

type InvoiceUploader_UpdateAttachmentServer interface {
	SendAndClose(*Response) error
	Recv() (*Attachment, error)
	grpc.ServerStream
}

type invoiceUploaderUpdateAttachmentServer struct {
	grpc.ServerStream
}

func (x *invoiceUploaderUpdateAttachmentServer) SendAndClose(m *Response) error {
	return x.ServerStream.SendMsg(m)
}

func (x *invoiceUploaderUpdateAttachmentServer) Recv() (*Attachment, error) {
	m := new(Attachment)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _InvoiceUploader_UpdateCounterPartyVAT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CounterPartyVAT)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InvoiceUploaderServer).UpdateCounterPartyVAT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.InvoiceUploader/UpdateCounterPartyVAT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InvoiceUploaderServer).UpdateCounterPartyVAT(ctx, req.(*CounterPartyVAT))
	}
	return interceptor(ctx, in, info, handler)
}

var _InvoiceUploader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.InvoiceUploader",
	HandlerType: (*InvoiceUploaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateXMLInvoice",
			Handler:    _InvoiceUploader_CreateXMLInvoice_Handler,
		},
		{
			MethodName: "UpdateCounterPartyVAT",
			Handler:    _InvoiceUploader_UpdateCounterPartyVAT_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateInvoicePreview",
			Handler:       _InvoiceUploader_UpdateInvoicePreview_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UpdateAttachment",
			Handler:       _InvoiceUploader_UpdateAttachment_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "invoices.proto",
}

// InvoiceGetterClient is the client API for InvoiceGetter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type InvoiceGetterClient interface {
	GetInvoicePreview(ctx context.Context, in *QueryInvoice, opts ...grpc.CallOption) (InvoiceGetter_GetInvoicePreviewClient, error)
	GetAttachments(ctx context.Context, in *QueryInvoice, opts ...grpc.CallOption) (InvoiceGetter_GetAttachmentsClient, error)
	GetAttachment(ctx context.Context, in *QueryAttachment, opts ...grpc.CallOption) (InvoiceGetter_GetAttachmentClient, error)
}

type invoiceGetterClient struct {
	cc *grpc.ClientConn
}

func NewInvoiceGetterClient(cc *grpc.ClientConn) InvoiceGetterClient {
	return &invoiceGetterClient{cc}
}

func (c *invoiceGetterClient) GetInvoicePreview(ctx context.Context, in *QueryInvoice, opts ...grpc.CallOption) (InvoiceGetter_GetInvoicePreviewClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InvoiceGetter_serviceDesc.Streams[0], "/services.InvoiceGetter/GetInvoicePreview", opts...)
	if err != nil {
		return nil, err
	}
	x := &invoiceGetterGetInvoicePreviewClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InvoiceGetter_GetInvoicePreviewClient interface {
	Recv() (*InvoicePreview, error)
	grpc.ClientStream
}

type invoiceGetterGetInvoicePreviewClient struct {
	grpc.ClientStream
}

func (x *invoiceGetterGetInvoicePreviewClient) Recv() (*InvoicePreview, error) {
	m := new(InvoicePreview)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *invoiceGetterClient) GetAttachments(ctx context.Context, in *QueryInvoice, opts ...grpc.CallOption) (InvoiceGetter_GetAttachmentsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InvoiceGetter_serviceDesc.Streams[1], "/services.InvoiceGetter/GetAttachments", opts...)
	if err != nil {
		return nil, err
	}
	x := &invoiceGetterGetAttachmentsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InvoiceGetter_GetAttachmentsClient interface {
	Recv() (*AttachmentsResponse, error)
	grpc.ClientStream
}

type invoiceGetterGetAttachmentsClient struct {
	grpc.ClientStream
}

func (x *invoiceGetterGetAttachmentsClient) Recv() (*AttachmentsResponse, error) {
	m := new(AttachmentsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *invoiceGetterClient) GetAttachment(ctx context.Context, in *QueryAttachment, opts ...grpc.CallOption) (InvoiceGetter_GetAttachmentClient, error) {
	stream, err := c.cc.NewStream(ctx, &_InvoiceGetter_serviceDesc.Streams[2], "/services.InvoiceGetter/GetAttachment", opts...)
	if err != nil {
		return nil, err
	}
	x := &invoiceGetterGetAttachmentClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type InvoiceGetter_GetAttachmentClient interface {
	Recv() (*AttachmentsResponse, error)
	grpc.ClientStream
}

type invoiceGetterGetAttachmentClient struct {
	grpc.ClientStream
}

func (x *invoiceGetterGetAttachmentClient) Recv() (*AttachmentsResponse, error) {
	m := new(AttachmentsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// InvoiceGetterServer is the server API for InvoiceGetter service.
type InvoiceGetterServer interface {
	GetInvoicePreview(*QueryInvoice, InvoiceGetter_GetInvoicePreviewServer) error
	GetAttachments(*QueryInvoice, InvoiceGetter_GetAttachmentsServer) error
	GetAttachment(*QueryAttachment, InvoiceGetter_GetAttachmentServer) error
}

// UnimplementedInvoiceGetterServer can be embedded to have forward compatible implementations.
type UnimplementedInvoiceGetterServer struct {
}

func (*UnimplementedInvoiceGetterServer) GetInvoicePreview(req *QueryInvoice, srv InvoiceGetter_GetInvoicePreviewServer) error {
	return status.Errorf(codes.Unimplemented, "method GetInvoicePreview not implemented")
}
func (*UnimplementedInvoiceGetterServer) GetAttachments(req *QueryInvoice, srv InvoiceGetter_GetAttachmentsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAttachments not implemented")
}
func (*UnimplementedInvoiceGetterServer) GetAttachment(req *QueryAttachment, srv InvoiceGetter_GetAttachmentServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAttachment not implemented")
}

func RegisterInvoiceGetterServer(s *grpc.Server, srv InvoiceGetterServer) {
	s.RegisterService(&_InvoiceGetter_serviceDesc, srv)
}

func _InvoiceGetter_GetInvoicePreview_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryInvoice)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InvoiceGetterServer).GetInvoicePreview(m, &invoiceGetterGetInvoicePreviewServer{stream})
}

type InvoiceGetter_GetInvoicePreviewServer interface {
	Send(*InvoicePreview) error
	grpc.ServerStream
}

type invoiceGetterGetInvoicePreviewServer struct {
	grpc.ServerStream
}

func (x *invoiceGetterGetInvoicePreviewServer) Send(m *InvoicePreview) error {
	return x.ServerStream.SendMsg(m)
}

func _InvoiceGetter_GetAttachments_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryInvoice)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InvoiceGetterServer).GetAttachments(m, &invoiceGetterGetAttachmentsServer{stream})
}

type InvoiceGetter_GetAttachmentsServer interface {
	Send(*AttachmentsResponse) error
	grpc.ServerStream
}

type invoiceGetterGetAttachmentsServer struct {
	grpc.ServerStream
}

func (x *invoiceGetterGetAttachmentsServer) Send(m *AttachmentsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _InvoiceGetter_GetAttachment_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryAttachment)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InvoiceGetterServer).GetAttachment(m, &invoiceGetterGetAttachmentServer{stream})
}

type InvoiceGetter_GetAttachmentServer interface {
	Send(*AttachmentsResponse) error
	grpc.ServerStream
}

type invoiceGetterGetAttachmentServer struct {
	grpc.ServerStream
}

func (x *invoiceGetterGetAttachmentServer) Send(m *AttachmentsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _InvoiceGetter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.InvoiceGetter",
	HandlerType: (*InvoiceGetterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetInvoicePreview",
			Handler:       _InvoiceGetter_GetInvoicePreview_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAttachments",
			Handler:       _InvoiceGetter_GetAttachments_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAttachment",
			Handler:       _InvoiceGetter_GetAttachment_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "invoices.proto",
}
